FUNCTION(LOAD_CONAN_BUILD_INFO)
    GET_PROPERTY(IS_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    IF (IS_MULTI_CONFIG)
        STRING(TOLOWER ${CMAKE_CONFIGURATION_TYPES} CMAKE_BUILD_TYPE_LOWER)
    ELSE()
        STRING(TOLOWER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_LOWER)
    ENDIF()
    # Find Conan cmake definition
    FIND_FILE(CONAN_${PROJECT_NAME}_BUILD_INFO
        conanbuildinfo.cmake
        PATHS
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}/build
        ${CMAKE_CURRENT_SOURCE_DIR}/../build
        ${CMAKE_CURRENT_BINARY_DIR}
        ${CMAKE_SOURCE_DIR}
        ${CMAKE_SOURCE_DIR}/build
        ${CMAKE_SOURCE_DIR}/../build
        ${CMAKE_BINARY_DIR}
    )
    # Include Conan definition and set RPATHS
    INCLUDE(${CONAN_${PROJECT_NAME}_BUILD_INFO})
    CONAN_BASIC_SETUP(TARGETS KEEP_RPATHS)

    SET(CONAN_BUILD_INFO_FOUND TRUE PARENT_SCOPE)
    SET(GTEST_ROOT ${CONAN_GTEST_ROOT} PARENT_SCOPE)

    SET(NAMESPACE CONAN_PKG PARENT_SCOPE)
ENDFUNCTION()
